version: '3.3'
services: 
  web:
    build: 
      context: ./php
      dockerfile: Dockerfile
    container_name: php73
    depends_on: 
      - db
      - phpmyadmin
    volumes: 
      - ./php:/var/www/html/
    ports: 
      - 8000:80
  db:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: test_root_password
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports: 
      - 6033:3306
  phpmyadmin:
    container_name: myadmin
    image: phpmyadmin
    restart: always
    depends_on: 
      - db
    environment: 
      MYSQL_ROOT_PASSWORD: Dimoolla20
    ports: 
      - 8001:80
